CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE CHECK(LENGTH(username) >= 4),
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);